#!/usr/bin/env ruby

require 'htmlentities'
require 'notifaction'
require 'pathname'

require_relative "../lib/uniconvert/setup.rb"
require_relative "../lib/uniconvert.rb"

setup = Uniconvert::Setup.new

# include all converters
setup.load_converters

# convert input to HTML-safe characters
setup.execute_conversion